### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by f-nunez** [f-nunez/VeterinaryClinic#29]
As a product owner, I want turn the current applications into Docker containers as an alternative for development and deployment.

SharedKernel's nuget packages should be imported as local source on each required solution to avoid developers build those nugets on their own.

An explicit folder should be created for handling Patient's photos between solutions on the repository for fast development. Consider that could be mounted into a Volume on ClinicManagement Api and Scheduling Api.

Self-Signed SSL should be implemented on each deployment.

Configure local host/machine DNS to simulate a DNS server. Naming subdomains for each public app like clinicmanagement-blazor.vc.local, scheduling-blazor.vc.local and identity-api.vc.local.

On each existing application it must perform the following tasks:
Scaffold application.
Create a Dockerfile.
Create a Docker ignore file.
Build image.
Run container.

Criteria:
- Allocate nugets into a folder called local_nugets. Example: "\SharedKernel\local_nugets\Fnunez.VeterinaryClinic.SharedKernel.Domain.1.3.2.nupkg"
- Import SharedKernel nugets in each required solution (ClinicManagement, ClinicManagementNotifications, Scheduling, SchedulingNotifications, SchedulingEmailSender).
- Add Docker's ignore file in each solution.
- Add Dockerfile for building image in each solution.
- Add and configure a Docker compose to build the entire solution.
- Add a file server (Samba) to improve sharing data between Backend.
- Add at least a custom network to avoid default Docker network.
- Expose required ports for inbound and outbound to talk to other containers.
- Assign ports from 14330+ for databases forwarding the default port 1433 for local debugging through SQL Manager Studio.
- Databases should be accessed from host machine through 127.0.0.1 plus its connection string properties.

Plus (Extra):
- Each boundary context should have its own virtual network
- RabbitMq should have its own virtual network shared through required boundary context
- File server should have its own virtual network shared to required boundary context
- Deploy (Frontend) with a DNS name instead of localhost
- Add and run self-certified in each container
- Add multiple environment stages (Local Development, Docker Development, Docker Nginx)

**Comment by harshit82** [comment]
Hey @f-nunez, I am new to Docker and am looking for opportunities to learn and contribute. 
Can I work on this?

**Comment by f-nunez** [comment]
Hi @harshit82 , sorry for the delay. Glad to see you interested in contributing.

Actually, I must have to work on this because it requires changes to the requirements.

But after finish this, I can create and let you take a feature about implementing Docker best practices (covering standard conventions, security/vulnerabilities, race conditions, and things like that).

**Comment by harshit82** [comment]
How thoughtful of you, thanks.
